version: "3.8"

services:
  apprise:
    image: caronc/apprise:${APPRISE_CONTAINER_VERS}
    container_name: apprise
    hostname: apprise
    ports:
      - 8000:8000
    # user: "www-data:www-data"
    volumes:
      # - ${APPRISE_WEBAPP_DIR}:/opt/apprise/webapp:ro
      - ${APPRISE_CONFIG_DIR}/config:/config
      - ${APPRISE_CONFIG_DIR}/plugin:/plugin
      - ${APPRISE_CONFIG_DIR}/attach:/attach
      # if uncommenting the below, you will need to type the following
      # Note: if you opt for bind mount config file consider setting env var APPRISE_STATEFUL_MODE to simple with appropriate file format
      # otherwise the django instance won't have permissions to write
      # to the directory correctly:
      #   $> chown -R 33:33 ./config
      #   $> chmod -R 775 ./config
      # - ./config:/config:rw
      # Note: The attachment directory can be exposed outside of the container if required
      #   $> chown -R 33:33 ./attach
      #   $> chmod -R 775 ./attach
      # - ./attach:/attach:rw